---
language: ruby
sudo: false
cache: bundler
before_script:
  - bundle install --path .vendor/bundle
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
script:
  - bundle exec rake validate
notifications:
  email: false
